# Generated by Django 2.2 on 2019-09-09 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0003_featurematrix_is_prediction_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccimsanalysiswrapper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 9, 14, 45, 11, 667715, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
