# Generated by Django 2.2 on 2019-09-09 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0004_mccimsanalysiswrapper_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
