# Generated by Django 2.2 on 2019-11-12 13:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0006_gcmspeakdetectionresult_gcmspredefinedpeakdetectionfileset_gcmsrawmeasurement_gcmsunlinkedpeakdetect'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCMSPeakDetectionFileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('peak_detection_results', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('class_label_processed_id_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('class_label_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCMSFileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_files', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('class_label_processed_id_dict', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peak_detection_fileset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breath.GCMSPeakDetectionFileSet')),
            ],
        ),
    ]
