# Generated by Django 2.2 on 2019-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0007_gcmsfileset_gcmspeakdetectionfileset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccimsanalysiswrapper',
            name='is_gcms_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
