# Generated by Django 2.2 on 2019-11-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0008_mccimsanalysiswrapper_is_gcms_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccimsanalysiswrapper',
            name='gcms_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='breath.GCMSFileSet'),
        ),
    ]
