# Generated by Django 2.2 on 2019-11-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breath', '0010_gcmspeakdetectionfileset_has_unlinked_peak_detection_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcmspeakdetectionfileset',
            name='peak_detection_method_name',
            field=models.CharField(default='CUSTOM', max_length=100),
        ),
    ]
